backend:
  name: git-gateway
  branch: master
  # repo: Maufive/matsake2.0

media_folder: static/personal/images
public_folder: /images

collections:
  - name: personal
    label: Personal
    folder: "static/personal"
    create: true
    identifier_field: namn
    fields:
      - { name: namn, label: Fullständigt namn, widget: string }
      - { name: titel, label: Jobbtitel, widget: string }
      - { name: nummer, label: Telefonnummer, widget: string }
      - { name: mail, label: Email, widget: string }
      - { name: image, label: Foto, widget: image }

  - name: oppettider
    label: Öppettider
    folder: "static/oppettider"
    create: true
    identifier_field: "mon-fri"
    fields:
      - { name: "mon-fri", label: "Måndag - Fredag", widget: string }
      - { name: "sat", label: "Lördag", widget: string }
      - { name: "sun", label: "Söndag", widget: string }
